spring:
  jpa:
    show-sql: true
    propertise:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot


#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:XE
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    username: scott
#    password: tiger
#    server:
#      port: 9090